FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src
COPY ./../ .
RUN dotnet build
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CulDeSacServicesOrchestration.Api.dll"]